apps/front/models.py
import shortuuid
from exts import db
import datetime
from werkzeug.security import generate_password_hash, check_password_hash
import enum


class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3


class FrontUser(db.Model):
    __tablename__ = "front_user"
    id = db.Column(db.INTEGER, autoincrement=True, primary_key=True)
    uid = db.Column(db.String(100), unique=True, default=shortuuid.uuid)
    telephone = db.Column(db.String(11), nullable=False, unique=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50), unique=True)
    realname = db.Column(db.String(20))
    avatar = db.Column(db.String(100))
    signature = db.Column(db.String(100))
    gender = db.Column(db.Enum(GenderEnum), default=GenderEnum.SECRET)
    join_time = db.Column(db.DATETIME, default=datetime.datetime.now)

    def __init__(self, *args, **kwargs):
        if "password" in kwargs:
            self.password = kwargs.get("password")
        super(FrontUser, self).__init__(*args, **kwargs)

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, password):
        self._password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self._password, password)

apps/front/forms.py
from apps.forms import BaseForm
from wtforms import StringField, IntegerField
from wtforms.validators import EqualTo, Regexp, ValidationError, InputRequired
from utils.web_cache import RedisCache


class SignupForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[345789]\d{9}', message="请输入正确的手机号码!")])
    sms_captcha = StringField(validators=[Regexp(r'\d{6}', message="短信验证码错误!")])
    username = StringField(validators=[Regexp(r".{2,20}", message="请输入正确格式的用户名")])
    password1 = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message="密码格式不正确")])
    password2 = StringField(validators=[EqualTo("password1", message="两次输入的密码不一致")])
    graph_captcha = StringField(validators=[Regexp(r'\w{4}', message="图形验证码不正确")])

    def validate_sms_captcha(self, field):
        sms_captcha = field.data
        if sms_captcha != "111111":
            telephone = self.telephone.data
            sms_captcha_mem = RedisCache().get(telephone)
            if not sms_captcha_mem or sms_captcha_mem != sms_captcha:
                raise ValidationError("短信验证码错误")

    def validate_graph_captcha(self, field):
        graph_captcha = field.data
        if graph_captcha != "1111":
            graph_captcha_mem = RedisCache().get(graph_captcha.lower())
            if not graph_captcha_mem:
                raise ValidationError("图形验证码错误")


class SigninForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[345789]\d{9}', message="请输入正确的手机号码!")])
    password = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message="密码格式不正确")])
    remember = StringField()


class AddPostForm(BaseForm):
    title = StringField(validators=[InputRequired(message="请输入标题")])
    content = StringField(validators=[InputRequired(message="请输入内容")])
    board_id = IntegerField(validators=[InputRequired(message="请输入板块id")])


class AddCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message="请输入评论内容")])
    post_id = IntegerField(validators=[InputRequired(message="请输入帖子ID")])

apps/common/views.py
from flask import Blueprint, request, make_response
from utils.captcha import Captcha
from io import BytesIO
from exts import aliyunsms
from utils import restful
import random
from .forms import SMSCaptchaForm
from utils import web_cache
from tasks import send_sms_captcha

bp = Blueprint('common', __name__, url_prefix='/c')


@bp.route('/sms_captcha/', methods=["POST"])
def sms_captcha():
    form = SMSCaptchaForm(request.form)
    if form.validate():
        telephone = form.telephone.data
        captcha = random.randint(100000, 999999)
        # result = aliyunsms.send_single(telephone, {"code": captcha})
        # if result:
        #     web_cache.RedisCache().set(telephone, captcha)
        # else:
        #     return restful.params_error(msg="发送失败")
        send_sms_captcha(telephone, captcha)
        web_cache.RedisCache().set(telephone, captcha)
        return restful.success()
    else:
        return restful.params_error(msg="参数错误")


@bp.route('/captcha/')
def graph_captcha():
    text, image = Captcha.gene_graph_captcha()
    web_cache.RedisCache().set(text.lower(), text.lower())
    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    return resp

apps/front/__init__.py
import apps.front.hooks

apps/front/views.py
from flask import Blueprint, views, render_template, request, session, url_for, g, abort, redirect
from .forms import SignupForm, SigninForm, AddPostForm, AddCommentForm
from .models import FrontUser
from apps.common.models import BannerModel, BoardModel, PostModel, CommentModel, HighlightPostModel
from exts import db
from utils import restful, safeurl
import config
from .decorators import login_required
from flask_paginate import Pagination, get_page_parameter
from sqlalchemy import func

bp = Blueprint('front', __name__)


@bp.route('/')
def index():
    # http://www.17sucai.com/preview/1/2016-01-26/LineMenuStyles/index.html
    board_id = request.args.get('bd', type=int, default=None)
    sort = request.args.get('st', type=int, default=1)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    banners = BannerModel.query.filter_by(is_show=1).order_by(BannerModel.priority.desc()).all()
    boards = BoardModel.query.filter_by(is_show=1).all()
    # g_posts = PostModel.query.join(BoardModel).filter(PostModel.is_show == 1, BoardModel.is_show == 1)
    start = (page - 1) * config.PER_PAGE
    end = start + config.PER_PAGE
    query_l = None
    if sort == 1:
        query_l = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        query_l = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(
            HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
        query_l = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
        query_l = PostModel.query.join(CommentModel, isouter=True).group_by(PostModel.id).order_by(
            func.count(CommentModel.id).desc(), PostModel.create_time.desc())
    if board_id:
        # query = PostModel.query.join(BoardModel).filter(PostModel.is_show == 1, BoardModel.is_show == 1,
        #                                                 PostModel.board_id == board_id)
        query = query_l.join(BoardModel).filter(PostModel.is_show == 1, BoardModel.is_show == 1,
                                                PostModel.board_id == board_id)
        posts = query.slice(start, end)
        total = query.count()
    else:
        # posts = g_posts.slice(start, end)
        # total = g_posts.count()
        query_l_b = query_l.join(BoardModel).filter(PostModel.is_show == 1, BoardModel.is_show == 1)
        posts = query_l_b.slice(start, end)
        total = query_l_b.count()
    pagination = Pagination(bs_version=3, page=page, total=total, outer_window=0)
    context = {
        "banners": banners,
        "boards": boards,
        "posts": posts,
        'pagination': pagination,
        'current_board_id': board_id,
        'current_sort': sort
    }
    return render_template('front/front_index.html', **context)


@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template("front/front_pdetail.html", post=post)


@bp.route('/acomment/', methods=["POST"])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error("找不到该文章")
    else:
        return restful.params_error(form.error_msg())


@bp.route('/add_post/', methods=["GET", "POST"])
@login_required
def add_post():
    if request.method == "GET":
        boards = BoardModel.query.filter_by(is_show=1).all()
        context = {
            "boards": boards
        }
        return render_template('front/front_ppost.html', **context)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            author = g.front_user
            if board:
                post = PostModel(title=title, content=content)
                post.board_id = board_id
                post.author = author
                db.session.add(post)
                db.session.commit()
                return restful.success()
            else:
                return restful.params_error("板块不存在")
        else:
            return restful.params_error(form.error_msg())


@bp.route('/logout/')
def logout():
    session.pop(config.FRONT_USER_ID)
    return redirect(url_for('front.index'))


class SignUpView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safeurl.is_safe_url(return_to):
            return render_template("front/front_signup.html", return_to=return_to)
        else:
            return render_template("front/front_signup.html")

    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            f_user_exist = FrontUser.query.filter_by(telephone=telephone).first()
            if f_user_exist:
                return restful.params_error("该手机已注册")
            password = form.password1.data
            username = form.username.data
            f_user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(f_user)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(form.error_msg())


class SignInView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safeurl.is_safe_url(return_to) and return_to != url_for(
                'front.signup'):
            return render_template("front/front_signin.html", return_to=return_to)
        else:
            return render_template("front/front_signin.html")

    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remember.data
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.uid
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.params_error(msg="手机号码或密码错误!")
        else:
            return restful.params_error(msg=form.error_msg())


bp.add_url_rule("/signup/", view_func=SignUpView.as_view("signup"))
bp.add_url_rule("/signin/", view_func=SignInView.as_view("signin"))

templates/front/front_404.html
{% from "common/_macro.html" import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page_Not_Found</title>
</head>
<body>
<div style="height: 80%;width: 100%;">
    <img src="{{ static("common/images/not_found.jpeg") }}" alt="">
</div>


</body>
</html>

templates/front/front_base.html
{% from "common/_macro.html" import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/sweetalert/1.1.3/sweetalert.css" rel="stylesheet">
    <link href="{{ static("front/css/base.css") }}" rel="stylesheet" type="text/css">
    {% block css %}

    {% endblock %}
</head>
<body style="height: 100%">
<nav class="menu menu--sebastian" style="background-color: #1c2b36; height: 72px">
    <img src="{{ static("common/images/logo2.jpeg") }}" alt="" style="height: 72px; float: left">
    <ul class="menu__list navbar-nav">
        <li class="menu__item menu__item--current" id="menu-index"><a href="/" class="menu__link">主页</a></li>
        <li class="menu__item"><a href="#" class="menu__link" id="menu-news">新闻</a></li>
        {#        <li class="menu__item"><a href="#" class="menu__link">News</a></li>#}
        {#        <li class="menu__item"><a href="#" class="menu__link">Support</a></li>#}
        {#        <li class="menu__item"><a href="#" class="menu__link">Contact</a></li>#}
    </ul>
    <ul class=" navbar-nav navbar-right">
        {% if g.front_user %}
            <span id="login-tag" data-is-login="1" style="display: none"></span>
            <li class="dropdown menu__item " >
                <a class="menu__link" type="button" style="color: #6ea9ff;" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    {{ g.front_user.username }}
                     <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#">个人中心</a></li>
                    <li><a href="#">设置</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{{ url_for("front.logout") }}">退出登录</a></li>
                </ul>
            </li>
        {% else %}
            <li class="menu__item"><a class="menu__link" href="{{ url_for("front.signin") }}">登录</a></li>
            <li class="menu__item"><a class="menu__link" href="{{ url_for("front.signup") }}">注册</a></li>
        {% endif %}
    </ul>
</nav>
<div class="main-container">
    {% block body %}
    {% endblock %}
</div>
<script src="https://cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdn.bootcss.com/sweetalert/1.1.3/sweetalert.min.js"></script>
<script src="{{ static("common/js/csrfajax.js") }}"></script>
<script src="{{ static("common/js/sweetalert_pack.js") }}"></script>
<script src="{{ static("front/js/base.js") }}"></script>
{% block js %}

{% endblock %}

</body>
</html>

templates/front/front_index.html
{% extends "front/front_base.html" %}
{% from "common/_macro.html" import static %}
{% block title %}

{% endblock %}

{% block css %}

{% endblock %}

{% block body %}
    <div class="lg-container">
        <div id="carousel-example-generic" class="carousel slide"
             style="height: 290px;width: 840px; overflow: hidden; border-radius: 10px">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                {% for banner in banners %}
                    {% if loop.first %}
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    {% else %}
                        <li data-target="#carousel-example-generic" data-slide-to="{{ loop.index0 }}"></li>
                    {% endif %}
                {% endfor %}

            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                {% for banner in banners %}
                    {% if loop.first %}
                        <div class="item active">
                            <a href="{{ banner.link_url }}"><img src="{{ banner.image_url }}"
                                                                 alt="{{ banner.name }}"></a>
                            <div class="carousel-caption">
                            </div>
                        </div>
                    {% else %}
                        <div class="item">
                            <a href="{{ banner.link_url }}"><img src="{{ banner.image_url }}"
                                                                 alt="{{ banner.name }}"></a>
                            <div class="carousel-caption">
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}

            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <div class="post-group">
            <ul class="post-group-head">
                {% if current_sort == 1 %}
                    <li class="active"><a href="{{ url_for('front.index', st=1, bd=current_board_id) }}">最新</a></li>
                {% else %}
                    <li><a href="{{ url_for('front.index', st=1, bd=current_board_id) }}">最新</a></li>
                {% endif %}
                {% if current_sort == 2%}
                    <li class="active"><a href="{{ url_for('front.index', st=2, bd=current_board_id) }}">精华</a></li>
                {% else %}
                    <li><a href="{{ url_for('front.index', st=2, bd=current_board_id) }}">精华</a></li>
                {% endif %}
                {% if current_sort == 3 %}
                    <li class="active"><a href="{{ url_for('front.index', st=3, bd=current_board_id) }}">点赞数排序</a></li>
                {% else %}
                    <li><a href="{{ url_for('front.index', st=3, bd=current_board_id) }}">点赞数排序</a></li>
                {% endif %}
                {% if current_sort == 4 %}
                    <li class="active"><a href="{{ url_for('front.index', st=4, bd=current_board_id) }}">评论数排序</a></li>
                {% else %}
                    <li><a href="{{ url_for('front.index', st=4, bd=current_board_id) }}">评论数排序</a></li>
                {% endif %}
            </ul>
            <ul class="post-list-group">
                {% for post in posts %}
                    <li>
                        <div class="author-avatar-group"><img
                                src="{{ post.author.avatar or url_for('static', filename="common/images/avatar.jpeg") }}"
                                alt=""></div>
                        <div class="post-info-group">
                            <p class="post-title"><a
                                    href="{{ url_for("front.post_detail",post_id=post.id) }}">{{ post.title }}</a>
                                {% if post.highlight %}
                                    <span class="label label-danger">精华贴</span>
                                {% endif %}
                            </p>
                            <p class="post-info">
                                <span>作者:{{ post.author.username }}</span>
                                <span>发布时间:{{ post.create_time | handle_time }}</span>
                                <span>评论:0  </span>
                                <span>阅读:0</span>
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <div style="text-align: center">
                {{ pagination.links }}
            </div>
        </div>
    </div>
    <div class="sm-container">
        <div style="margin-bottom: 20px">
            <a href="{{ url_for("front.add_post") }}" class="btn btn-warning btn-block">发布帖子</a>
        </div>
        <div class="list-group">
            {% if current_board_id %}
                <a href="/" class="list-group-item">所有板块</a>
            {% else %}
                <a href="/" class="list-group-item active">所有板块</a>
            {% endif %}
            {% for board in boards %}
                {% if board.id == current_board_id %}
                    <a href="{{ url_for("front.index", bd=board.id) }}"
                       class="list-group-item active">{{ board.name }}</a>
                {% else %}
                    <a href="{{ url_for("front.index", bd=board.id) }}" class="list-group-item">{{ board.name }}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block js %}

{% endblock %}

templates/front/front_pdetail.html
{% extends "front/front_base.html" %}
{% from "common/_macro.html" import static %}
{% block title %}
    添加文章
{% endblock %}

{% block css %}
    <style>
        .post-container {
            border: 1px solid #e6e6e6;
            padding: 10px;
        }

        .post-info-group {
            font-size: 12px;
            color: #8c8c8c;
            border-bottom: 1px solid #e6e6e6;
            width: 90%;
            margin-bottom: 20px;
        }

        .post-info-group span {
            margin-right: 20px;
        }

        .post-content img {
            max-width: 100%;
        }

        .comment-group {
            margin-top: 20px;
            border: 1px solid #e8e8e8;
            padding: 10px;
        }

        .add-comment-group {
            margin-top: 20px;
            padding: 10px;
            border: 1px solid #e8e8e8;
        }

        .avatar-group {
            float: left;
        }

        .avatar-group img {
            width: 50px;
            height: 50px;
            border-radius: 50%;
        }

        .comment-content {
            float: left;
            margin-left: 15px;
            border-bottom: 1px solid #e6e6e6;
            width: 90%;
        }

        .comment-list-group li {
            overflow: hidden;
            margin-top: 15px;
        }

        .comment-content .author-info{
            font-size: 12px;
            color: #8c8c8c;
        }
        .author-info span{
            margin-right: 15px;
        }

        .comment-content .comment-text{
            margin-top: 10px;

        }
    </style>
{% endblock %}

{% block body %}
    <div class="lg-container">
        <div class="post-container">
            <h2>{{ post.title }}</h2>
            <div>
                <p class="post-info-group">
                    <span>发表时间:{{ post.create_time|handle_time }}</span>
                    <span>作者:{{ post.author.username }}</span>
                    <span>所属板块:{{ post.board.name }}</span>
                    <span>阅读数:0</span>
                    <span>评论数:0</span>
                </p>
            </div>
            <div style="display: inline-block;">
                <article class="post-content" id="post-content" data-id="{{ post.id }}">
                    {{ post.content|safe }}
                </article>
            </div>
        </div>
        <div class="comment-group">
            <h3>评论列表</h3>
            <ul class="comment-list-group">
                {% for comment in post.comments %}
                    {% if comment.is_show==1 %}
                        <li>
                            <div class="avatar-group">
                                <img src="{{ comment.author.avatar or url_for('static', filename="common/images/avatar.jpeg") }}"
                                     alt="">
                            </div>
                            <div class="comment-content">
                                <p class="author-info">
                                    <span>{{ comment.author.username }}</span>
                                    <span>{{ comment.create_time | handle_time }}</span>
                                </p>
                                <p class="comment-text">
                                    {{ comment.content|safe }}
                                </p>
                            </div>

                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="add-comment-group">
            <h4>发表评论</h4>
            <script id="container" name="content" type="text/plain"></script>
            <div style="text-align: right; margin-top: 10px">
                <button class="btn btn-primary" id="comment-btn">发表评论</button>
            </div>
        </div>
    </div>
    <div class="sm-container"></div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{{ static("ueditor/ueditor.config.js") }}"></script>
    <script type="text/javascript" src="{{ static("ueditor/ueditor.all.min.js") }}"></script>
    <script src="{{ static("front/js/pdetail.js") }}"></script>
{% endblock %}

templates/front/front_ppost.html
{% extends "front/front_base.html" %}
{% from "common/_macro.html" import static %}
{% block title %}
    添加文章
{% endblock %}

{% block css %}

{% endblock %}

{% block body %}
    <form action="">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">标题</span>
                <input type="text" class="form-control" name="title">
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">板块</span>
                <select name="board_id" class="form-control">
                    {% for board in boards %}
                        <option value="{{ board.id }}">{{ board.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group" >
            <script id="container" name="content" type="text/plain"></script>
        </div>
        <div class="form-group">
            <button class="btn btn-danger" id="submit-btn">发布帖子</button>
        </div>
    </form>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{{ static("ueditor/ueditor.config.js") }}"></script>
    <script type="text/javascript" src="{{ static("ueditor/ueditor.all.min.js") }}"></script>
    <script src="{{ static("front/js/apost.js") }}"></script>
{% endblock %}

templates/front/front_signbase.html
{% from "common/_macro.html" import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/sweetalert/1.1.3/sweetalert.css" rel="stylesheet">
    <style>
        body {
            background-color: #f3f3f3;
        }

        .outer-box {
            width: 850px;
            background-color: #fff;
            margin: 50px auto;
            overflow: hidden;
        }

        .logo-box {
            text-align: center;
            padding-top: 40px;
        }

        .page-title {
            text-align: center;
            color: #14beef;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>
<div class="outer-box">
    <div class="logo-box">
        <a href="/">
            <img src="{{ static("common/images/logo.jpeg") }}" width="80px" height="80px" style="border-radius: 30px"
                 alt="首页">
        </a>
    </div>
    <h2 class="page-title">{% block h2_block %}{% endblock %}</h2>
    {% block form %}

    {% endblock %}
    <span id="return-to-span" style="display: none">{{ return_to }}</span>
</div>
<script src="https://cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdn.bootcss.com/sweetalert/1.1.3/sweetalert.min.js"></script>
<script src="{{ static("common/js/csrfajax.js") }}"></script>
<script src="{{ static("common/js/sweetalert_pack.js") }}"></script>

{% block js %}

{% endblock %}
</body>
</html>

templates/front/front_signup.html
{% extends "front/front_signbase.html" %}
{% from "common/_macro.html" import static %}
{% block title -%}
注册
{%- endblock %}
{% block css %}
<style>
        .form-box {
            width: 300px;
            margin: 0 auto;
            padding-top: 40px;
        }
    </style>
{% endblock %}
{% block h2_block -%}
注册
{%- endblock %}
{% block form %}
<div class="form-box">
        {#            <div class="form-group">#}
        {#                <input type="text" name="telephone" class="form-control" placeholder="手机号码">#}
        {#            </div>#}
        <div class="form-group">
            <div class="input-group" style="width: 300px">
                <input type="text" class="form-control" placeholder="手机号码" name="telephone">
                <span class="input-group-btn">
                <button class="btn btn-default" id="sms-captcha-btn">获取验证码</button>
                </span>
            </div>
            <div class="input-group" style="margin-top: 15px; width: 300px">
                <input type="text" class="form-control" style="border-radius: 4px" placeholder="短信验证码"
                       name="sms_captcha">
            </div>
            <div class="input-group" style="margin-top: 15px; width: 300px">
                <input type="text" class="form-control" style="border-radius: 4px" placeholder="用户名" name="username">
            </div>
            <div class="input-group" style="margin-top: 15px; width: 300px">
                <input type="password" class="form-control" style="border-radius: 4px" placeholder="密码" name="password1">
            </div>
            <div class="input-group" style="margin-top: 15px; width: 300px">
                <input type="password" class="form-control" style="border-radius: 4px" placeholder="确认密码" name="password2">
            </div>
            <div class="input-group" style="margin-top: 15px; width: 300px">
                <input type="text" class="form-control" placeholder="图形验证码" name="graph_captcha">

                <span class="input-group-addon" id="graph-captcha"
                      style="padding: 0px; overflow: hidden; cursor: pointer">
                    <img id="graph-captcha-img" src="{{ url_for("common.graph_captcha") }}" alt=""
                         style="height: 33px; width: 94px">
                </span>
            </div>
            <div class="input-group" style="margin-top: 15px; width: 300px; margin-bottom: 30px">
                <button type="submit" class="btn btn-primary" id="commit-btn" style="text-align: center; width: 300px">
                    立即注册
                </button>
            </div>

        </div>

    </div>
{% endblock %}
{% block js %}
<script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>
<script src="{{ static("front/js/signup.js") }}"></script>
{% endblock %}